namespace SilvaViridis.Common.CSharp.Consts
{
    public static class Comments
    {
        public const string C_Autogenerated = @"// ----------------
// <autogenerated/>
// ----------------";
    }
}
