using Microsoft.CodeAnalysis;

namespace SilvaViridis.Common.CSharp.Consts.Generators
{
    [Generator(LanguageNames.CSharp)]
    public class GlobalsGenerator : IIncrementalGenerator
    {
        public void Initialize(
            IncrementalGeneratorInitializationContext context
        ) => context.RegisterPostInitializationOutput(
            ctx => ctx.AddSource(
                "CSharp.Consts.Globals.g.cs",
                _globalsText
            )
        );

        private const string _prefix = "global using static SilvaViridis.Common.CSharp.Consts.";

        private const string _globalsText = @$"// ----------------
// <autogenerated/>
// ----------------

{_prefix}Comments;
{_prefix}Directives;
{_prefix}Extensions;
{_prefix}Keywords;
{_prefix}Namespaces;
{_prefix}Postfixes;
{_prefix}Prefixes;
";
    }
}
